export { default as Navigation } from '@iliestefa/wedding-soho/components/Navigation/Navigation.jsx';
export { default as Hero } from '@iliestefa/wedding-soho/components/Hero/Hero.jsx';
export { default as Story } from '@iliestefa/wedding-soho/components/Story/Story.jsx';
export { default as Countdown } from '@iliestefa/wedding-soho/components/Countdown/Countdown.jsx';
export { default as Events } from '@iliestefa/wedding-soho/components/Events/Events.jsx';
export { default as Schedule } from '@iliestefa/wedding-soho/components/Schedule/Schedule.jsx';
export { default as DressCode } from '@iliestefa/wedding-soho/components/DressCode/DressCode.jsx';
export { default as GiftRegistry } from '@iliestefa/wedding-soho/components/GiftRegistry/GiftRegistry.jsx';
export { default as RsvpForm } from '@iliestefa/wedding-soho/components/RsvpForm/RsvpForm.jsx';
export { default as Footer } from '@iliestefa/wedding-soho/components/Footer/Footer.jsx';
export { TemplateProvider } from '@iliestefa/wedding-soho/context';
export { PRESET_PALETTES } from '@iliestefa/wedding-soho/utils/palettes.js';
export const hasStory = true;
